name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
              sudo apt-get install -y --no-install-recommends \
              check
    - name: Build
      uses: lukka/run-cmake@v2.5
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        buildDirectory: '${{ runner.workspace }}/build/'

    - name: Test
      run: ctest --output-on-failure
      working-directory: '${{ runner.workspace }}/build/'
